### ISSUE TITLE
Error tracking and better validation

### ISSUE THREAD

**Issue by bpmct** [bpmct/donut-delivery#19]
- [ ] Environment var for error tracking service
- [ ] Look into Sentry
- [ ] Add validation for basically all functions
- [ ] Cool error screen?

**Comment by bpmct** [comment]
#25 will determine how errors are tracked :)
